#!/usr/bin/env sh

# Checks that all files referenced from Cabal are being committed.

set -e

is_tracked() {
    git ls-files $1 --modified --cached --error-unmatch 2>/dev/null >/dev/null
}

exit_code=0
for cabal in `find -name '*.cabal'`; do
    if ! is_tracked "$cabal"; then
        continue
    fi

    dir="`dirname $cabal`"
    pushd "$dir" >/dev/null
    sources="$(git cat-file blob :"`basename "$cabal"`" | cabal-list-sources)"
    for file in $sources; do
        if ! is_tracked "$file"; then
            echo >&2 "`basename "$0"`: error: forgot to git add $dir/$file"
            exit_code=1
        fi
    done
    popd >/dev/null
done

exit $exit_code
