#!/bin/sh

# Checks that all files referenced from Cabal are being committed.

is_tracked() {
    git ls-files $1 --modified --cached --error-unmatch 2>/dev/null >/dev/null
}

exit_code=0
for cabal in `find -name '*.cabal'`; do
    if ! is_tracked "$cabal"; then
        continue
    fi
    for file in `cabal-list-sources "$cabal"`; do
        if ! is_tracked "$file"; then
            echo >&2 "$(basename $0): error: forgot to git add $file"
            exit_code=1
        fi
    done
done

exit $exit_code
